openapi: 3.0.0
info:
  title: Phillips-Connect API
  version: '1.0'
  description: API Specification for Phillips-Connect Smart Trailer Solutions
  contact:
    name: Brent Whitney
    email: bwhitney@phillips-connect.com
servers:
  - url: 'https://api.phillips-connect.com'
    description: Prod API
paths:
  /reports:
    get:
      summary: Retrieve gateway reports
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  body:
                    type: array
                    items:
                      $ref: ./device-report/models/report.v1.yaml
                  total_reports:
                    type: integer
                    description: Total number of reports returned
                  current_page:
                    type: integer
                    description: Current page index
                  total_pages:
                    type: integer
                    description: Total number of pages returned
                  response_message:
                    type: string
                  status:
                    type: boolean
              examples:
                example-1:
                  value:
                    body:
                      - gateway_id: string
                        asset_id: string
                        vin: string
                        report_number: 0
                        event_datetime: '2012-04-21T18:25:43Z'
                        event_name: string
                        server_datetime: string
                        gateway_number: 0
                        summary:
                          latitude: '33.628342'
                          longitude: '-117.927933'
                          location_datetime: string
                          speed: '80.1'
                          heading: 0
                          current_power_source: battery
                          internal_temperature: 0
                          is_trip: true
                          odometer: 0
                          ambient_temperature: 0
                        internal_sensors:
                          - type: gps-sensor
                            latitude: '33.628342'
                            longitude: '-117.927933'
                            measurement_datetime: '2012-04-21T18:25:43Z'
                            speed: 0
                            HDOP: 1.6
                            satellite_count: 0
                            gps_accuracy: 2.3
                        peripheral_sensors:
                          - type: ABS
                            condition: healthy
                            odometer: 0
                            VIN: string
                            voltage: '11.23'
                            faults:
                              - SID: string
                                is_active: true
                                count: 0
                                FMI_code: string
                                FMI_description: string
                        debug_number: 0
                        gateway_sequence: 0
                        version: string
                    total_reports: 0
                    current_page: 0
                    total_pages: 0
                    response_message: string
                    status: true
                example-2:
                  value:
                    body:
                      - gateway_id: string
                        asset_id: string
                        vin: string
                        report_number: 0
                        event_datetime: '2012-04-21T18:25:43Z'
                        event_name: string
                        server_datetime: string
                        gateway_number: 0
                        summary:
                          latitude: '33.628342'
                          longitude: '-117.927933'
                          location_datetime: string
                          speed: '80.1'
                          heading: 0
                          current_power_source: battery
                          internal_temperature: 0
                          is_trip: true
                          odometer: 0
                          ambient_temperature: 0
                        internal_sensors:
                          - type: gps-sensor
                            latitude: '33.628342'
                            longitude: '-117.927933'
                            measurement_datetime: '2012-04-21T18:25:43Z'
                            speed: 0
                            HDOP: 1.6
                            satellite_count: 0
                            gps_accuracy: 2.3
                        peripheral_sensors:
                          - type: ABS
                            condition: healthy
                            odometer: 0
                            VIN: string
                            voltage: '11.23'
                            faults:
                              - SID: string
                                is_active: true
                                count: 0
                                FMI_code: string
                                FMI_description: string
                        debug_number: 0
                        gateway_sequence: 0
                        version: string
                    total_reports: 0
                    current_page: 0
                    total_pages: 0
                    response_message: string
                    status: true
            multipart/form-data:
              schema:
                type: object
                properties: {}
            text/html:
              schema:
                $ref: ./device-report/models/report.v1.yaml
            text/plain:
              schema:
                type: object
                properties:
                  '':
                    $ref: ./device-report/models/report.v1.yaml
                  total_reports:
                    type: integer
                    description: Total reports based on the search criteria specified in the request
                  current_page:
                    type: integer
                    description: Current page index
                  total_pages:
                    type: integer
                    description: Total number of pages based on the result set
          headers: {}
      operationId: get-device-report
      parameters:
        - schema:
            type: string
          in: query
          name: gateway-id
          description: |
            Required to search by gateway-id (imei). If the query-method is set to GATEWAY_NUMBER, the gateway-id must be specificied
        - schema:
            type: string
            enum:
              - DATETIME
              - REPORT_NUMBER
              - GATEWAY_NUMBER
              - LATEST
          in: query
          name: query-method
          description: Indicates how to query the server REPORT-NUMBER is a sequential number assigned for each report that is generated across all customer devicesGATEWAY_NUMBER is a sequential number assigned for each report that is generated per customer deviceDATETIME is the datetime of when the report is received by the PCT server
        - schema:
            type: string
          in: query
          name: from
          description: 'From: [server datetime | report number | gateway number]'
        - schema:
            type: string
          in: query
          name: to
          description: 'To: [server datetime | report number | gateway number]'
        - schema:
            type: integer
          in: query
          name: results-per-page
          description: Number of results per page. Default is 2000 records
        - schema:
            type: integer
          in: query
          name: page-index
          description: 'For a multi-page query, returns the specified page (from 1 to total_pages) '
      description: |-
        Returns historical gateway reports. Reports are generated based on PCT event types.

        Open ended queries will pull recent reports across all gateways for a given customer (based on the data you are authorized to see, or you can limit this by providing a gateway-id (imei). 

        For further filtering, you can pass in a query method and provide the appropriate 'from' and 'to'. See specific instructions in the appropriate fields.   
      tags:
        - Reports
      x-internal: true
    parameters: []
  /token/login:
    post:
      summary: Generate a PCT API token
      tags:
        - Security Token
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                  tokenType:
                    type: string
                    enum:
                      - Bearer
      operationId: post-token-login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      description: Generate a token to be used in API calls
      x-internal: true
  /asset/assign:
    post:
      summary: Asset association
      tags:
        - Asset
      responses:
        '200':
          description: OK
      operationId: post-asset
      description: Called when a gateway is installed on an asset
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                gateway_id:
                  type: string
                asset_id:
                  type: string
                event_datetime:
                  type: string
                  description: Time that the gateway was associated to the gateway
            examples:
              example-1:
                value:
                  gateway_id: string
                  asset_id: string
                  event_datetime: string
              example-2:
                value:
                  gateway_id: string
                  asset_id: string
                  event_datetime: string
        description: Associate an asset to a gateway
      x-internal: true
    parameters: []
  /asset/reassign:
    post:
      summary: Asset reassignment
      tags:
        - Asset
      responses:
        '200':
          description: OK
      operationId: post-asset-replace
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                gateway_id:
                  type: string
                old_asset_id:
                  type: string
                new_asset_id:
                  type: string
                event_datetime:
                  type: string
            examples:
              example-1:
                value:
                  gateway_id: string
                  old_asset_id: string
                  new_asset_id: string
                  event_datetime: string
              example-2:
                value:
                  gateway_id: string
                  old_asset_id: string
                  new_asset_id: string
                  event_datetime: string
        description: Move the gateway to a new asset
      description: Called when the gateway is moved to a different asset
      x-internal: true
    parameters: []
  /asset/unassign:
    post:
      summary: Asset dissociation
      tags:
        - Asset
      responses:
        '200':
          description: OK
      operationId: post-asset-remove
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                gateway_id:
                  type: string
                asset_id:
                  type: string
                event_datetime:
                  type: string
            examples:
              example-1:
                value:
                  gateway_id: string
                  asset_id: string
                  event_datetime: string
        description: Dissociate the asset from a gateway
      description: Called when the gateway is uninstalled on an asset
      x-internal: true
    parameters: []
components:
  schemas: {}
  securitySchemes:
    API Key - 1:
      type: http
      scheme: bearer
