openapi: 3.1.0
info:
  title: gateway
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /gateway:
    parameters: []
    get:
      summary: Gateway Operations
      tags: []
      responses:
        '200':
          description: User Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  body:
                    type: array
                    items:
                      $ref: '#/components/schemas/gateway'
                  current_index:
                    type: integer
                  total_records:
                    type: integer
                  response_message:
                    type: string
                  status:
                    type:
                      - string
                      - boolean
                  total_pages:
                    type: integer
              examples:
                example-1:
                  value:
                    body:
                      - imei: string
                        product_code: string
                        product_name: string
                        quantity_shipped: string
                        app_version: string
                        mcu_version: string
                        bin_version: string
                        ble_version: string
                        other1_version: string
                        other2_version: string
                        config1: string
                        config2: string
                        config3: string
                        config4: string
                        epicor_order_number: string
                        can: string
                        son: string
                        cellular: string
                        uuid: string
                        iccid: string
                        imsi: string
                        carrier_id: string
                        country_code: string
                        phone_number: string
                        sensors:
                          - sensor_id: string
                            type: string
                            mac_address: string
                            status: string
                            name: string
                            product_code: string
                            product_name: string
                        asset:
                          asset_id: string
                          assigned_name: string
                          category: string
                          comment: string
                          manufacturer: string
                          status: string
                          vin: string
                          vin_validated: true
                          year: string
                    current_index: 0
                    total_records: 0
                    response_message: string
                    status: string
                    total_pages: 0
                example-2:
                  value:
                    body:
                      - imei: string
                        product_code: string
                        product_name: string
                        quantity_shipped: string
                        app_version: string
                        mcu_version: string
                        bin_version: string
                        ble_version: string
                        other1_version: string
                        other2_version: string
                        config1: string
                        config2: string
                        config3: string
                        config4: string
                        epicor_order_number: string
                        can: string
                        son: string
                        cellular: string
                        uuid: string
                        iccid: string
                        imsi: string
                        carrier_id: string
                        country_code: string
                        phone_number: string
                        sensors:
                          - sensor_id: string
                            type: string
                            mac_address: string
                            status: string
                            name: string
                            product_code: string
                            product_name: string
                        asset:
                          asset_id: string
                          assigned_name: string
                          category: string
                          comment: string
                          manufacturer: string
                          status: string
                          vin: string
                          vin_validated: true
                          year: string
                    current_index: 0
                    total_records: 0
                    response_message: string
                    status: string
                    total_pages: 0
                example-3:
                  value:
                    body:
                      - imei: string
                        product_code: string
                        product_name: string
                        quantity_shipped: string
                        app_version: string
                        mcu_version: string
                        bin_version: string
                        ble_version: string
                        other1_version: string
                        other2_version: string
                        config1: string
                        config2: string
                        config3: string
                        config4: string
                        epicor_order_number: string
                        can: string
                        son: string
                        cellular: string
                        uuid: string
                        iccid: string
                        imsi: string
                        carrier_id: string
                        country_code: string
                        phone_number: string
                        sensors:
                          - sensor_id: string
                            type: string
                            mac_address: string
                            status: string
                            name: string
                            product_code: string
                            product_name: string
                        asset:
                          asset_id: string
                          assigned_name: string
                          category: string
                          comment: string
                          manufacturer: string
                          status: string
                          vin: string
                          vin_validated: true
                          year: string
                    current_index: 0
                    total_records: 0
                    response_message: string
                    status: string
                    total_pages: 0
        '201':
          description: Created
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '404':
          description: User Not Found
      operationId: gateways
      description: |-
        Returns the list of gateways.

        Open ended queries will pull gateways (based on the data you are authorized to see).

        For further filtering, you can pass in a query method and provide the appropriate parameters. See specific instructions in the appropriate fields.   
      parameters:
        - schema:
            type: string
          in: query
          name: customer_account_number
          description: passing this parameter will fetch gateway records for a customer account number
        - schema:
            type: integer
          in: query
          name: results-per-page
          description: Number of records per page returned.  Default is 2000
        - schema:
            type: integer
          in: query
          name: page-index
          description: 'For a multi-page query, returns the specified page (from 1 to total_pages) '
        - schema:
            type: string
          in: query
          name: gateway-id
          description: required to search by getway-id(imei)
        - schema:
            type: string
          in: query
          name: asset-id
      x-internal: false
    post:
      summary: ''
      operationId: post-gateway
      responses:
        '200':
          description: OK
      description: ''
  /sensor:
    get:
      summary: get list of sensor
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                x-examples:
                  example-1:
                    body:
                      - imei: string
                    current_index: 0
                    total_records: 0
                    response_message: string
                    status: string
                    total_pages: 0
                properties:
                  body:
                    type: array
                    uniqueItems: true
                    minItems: 1
                    items:
                      $ref: '#/components/schemas/sensor'
                  current_index:
                    type: number
                  total_records:
                    type: number
                  response_message:
                    type: string
                    minLength: 1
                  status:
                    type: string
                    minLength: 1
                  total_pages:
                    type: number
                required:
                  - body
                  - current_index
                  - total_records
                  - response_message
                  - status
                  - total_pages
              examples:
                example-1:
                  value:
                    body:
                      - sensor_id: string
                        type: string
                        mac_address: string
                        status: string
                        name: string
                        product_code: string
                        product_name: string
                    current_index: 0
                    total_records: 0
                    response_message: string
                    status: string
                    total_pages: 0
                example-2:
                  value:
                    body:
                      - sensor_id: string
                        type: string
                        mac_address: string
                        status: string
                        name: string
                        product_code: string
                        product_name: string
                    current_index: 0
                    total_records: 0
                    response_message: string
                    status: string
                    total_pages: 0
                example-3:
                  value:
                    body:
                      - sensor_id: string
                        type: string
                        mac_address: string
                        status: string
                        name: string
                        product_code: string
                        product_name: string
                    current_index: 0
                    total_records: 0
                    response_message: string
                    status: string
                    total_pages: 0
      operationId: get-sensor
      parameters:
        - schema:
            type: integer
          in: query
          name: page-index
        - schema:
            type: integer
          in: query
          name: results-per-page
        - schema:
            type: string
          in: query
          name: gateway-id
        - schema:
            type: string
          in: query
          name: sensor-id
        - schema:
            type: string
          in: query
          name: asset-id
  /asset:
    post:
      summary: ''
      operationId: post-asset
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                gateway_id:
                  type: string
                  minLength: 1
                asset_id:
                  type: string
                  minLength: 1
                event_datetime:
                  type: string
                  minLength: 1
              required:
                - gateway_id
                - asset_id
                - event_datetime
              x-examples:
                example-1:
                  gateway_id: string
                  asset_id: string
                  event_datetime: string
    parameters: []
    get:
      summary: ''
      operationId: get-asset
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                x-examples:
                  example-1:
                    body:
                      - asset_id: string
                        type: string
                        mac_address: string
                        status: string
                        name: string
                        product_code: string
                        product_name: string
                    current_index: 0
                    total_records: 0
                    response_message: string
                    status: string
                    total_pages: 0
                properties:
                  body:
                    type: array
                    uniqueItems: true
                    minItems: 1
                    items:
                      $ref: '#/components/schemas/asset'
                  current_index:
                    type: number
                  total_records:
                    type: number
                  response_message:
                    type: string
                    minLength: 1
                  status:
                    type: string
                    minLength: 1
                  total_pages:
                    type: number
                required:
                  - body
                  - current_index
                  - total_records
                  - response_message
                  - status
                  - total_pages
              examples:
                example-1:
                  value:
                    body:
                      - asset_id: string
                        assigned_name: string
                        category: string
                        comment: string
                        manufacturer: string
                        status: string
                        vin: string
                        year: string
                    current_index: 0
                    total_records: 0
                    response_message: string
                    status: string
                    total_pages: 0
  /asset/assign:
    post:
      summary: ''
      operationId: post-asset-assign
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
  /asset/reassign:
    post:
      summary: ''
      operationId: post-asset-reassign
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
  /asset/unassign:
    post:
      summary: ''
      operationId: post-asset-unassign
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties: {}
components:
  schemas:
    gateway:
      description: ''
      type: object
      x-examples:
        example-1:
          imei: string
          product_code: string
          product_name: string
          quantity_shipped: string
          app_version: string
          mcu_version: string
          bin_version: string
          ble_version: string
          other1_version: string
          other2_version: string
          config1: string
          config2: string
          config3: string
          config4: string
          epicor_order_number: string
          can: string
          son: string
          cellular: string
          uuid: string
          iccid: string
          imsi: string
          carrier_id: string
          country_code: string
          phone_number: string
      properties:
        imei:
          type: string
          minLength: 1
        product_code:
          type: string
          minLength: 1
        product_name:
          type: string
          minLength: 1
        quantity_shipped:
          type: string
          minLength: 1
        app_version:
          type: string
          minLength: 1
        mcu_version:
          type: string
          minLength: 1
        bin_version:
          type: string
          minLength: 1
        ble_version:
          type: string
          minLength: 1
        other1_version:
          type: string
          minLength: 1
        other2_version:
          type: string
          minLength: 1
        config1:
          type: string
          minLength: 1
        config2:
          type: string
          minLength: 1
        config3:
          type: string
          minLength: 1
        config4:
          type: string
          minLength: 1
        epicor_order_number:
          type: string
          minLength: 1
        can:
          type: string
          minLength: 1
        son:
          type: string
          minLength: 1
        cellular:
          type: string
          minLength: 1
        uuid:
          type: string
          minLength: 1
        iccid:
          type: string
          minLength: 1
        imsi:
          type: string
          minLength: 1
        carrier_id:
          type: string
          minLength: 1
        country_code:
          type: string
          minLength: 1
        phone_number:
          type: string
          minLength: 1
        sensors:
          type: array
          items:
            $ref: '#/components/schemas/sensor'
        asset:
          $ref: '#/components/schemas/asset'
      required:
        - imei
        - product_code
        - product_name
        - quantity_shipped
        - app_version
        - mcu_version
        - bin_version
        - ble_version
        - other1_version
        - other2_version
        - config1
        - config2
        - config3
        - config4
        - epicor_order_number
        - can
        - son
        - cellular
        - uuid
        - iccid
        - imsi
        - carrier_id
        - country_code
        - phone_number
      examples:
        - imei: string
          product_code: string
          product_name: string
          quantity_shipped: string
          app_version: string
          mcu_version: string
          bin_version: string
          ble_version: string
          other1_version: string
          other2_version: string
          config1: string
          config2: string
          config3: string
          config4: string
          epicor_order_number: string
          can: string
          son: string
          cellular: string
          uuid: string
          iccid: string
          imsi: string
          carrier_id: string
          country_code: string
          phone_number: string
          sensors:
            - sensor_id: string
              type: string
              mac_address: string
              status: string
              name: string
              product_code: string
              product_name: string
          asset:
            asset_id: string
            assigned_name: string
            category: string
            comment: string
            manufacturer: string
            status: string
            vin: string
            vin_validated: true
            year: string
    sensor:
      description: ''
      type: object
      properties:
        sensor_id:
          type: string
          minLength: 1
        type:
          type: string
          minLength: 1
        mac_address:
          type: string
          minLength: 1
        status:
          type: string
          minLength: 1
        name:
          type: string
          minLength: 1
        product_code:
          type: string
          minLength: 1
        product_name:
          type: string
          minLength: 1
      required:
        - sensor_id
        - type
        - mac_address
        - status
        - name
        - product_code
        - product_name
      x-examples:
        example-1:
          sensor_id: string
          type: string
          mac_address: string
          status: string
          name: string
          product_code: string
          product_name: string
      examples:
        - sensor_id: string
          type: string
          mac_address: string
          status: string
          name: string
          product_code: string
          product_name: string
    asset:
      description: ''
      type: object
      x-examples:
        example-1:
          asset_id: ''
          assigned_name: string
          category: string
          comment: string
          manufacturer: string
          status: string
          vin: string
          vin_validated: true
          year: string
      examples:
        - asset_id: string
          assigned_name: string
          category: string
          comment: string
          manufacturer: string
          status: string
          vin: string
          year: string
      properties:
        asset_id:
          type: string
        assigned_name:
          type: string
          minLength: 1
        category:
          type: string
          minLength: 1
        comment:
          type: string
          minLength: 1
        manufacturer:
          $ref: '#/components/schemas/organization'
        status:
          type: string
          minLength: 1
        vin:
          type: string
          minLength: 1
        vin_validated:
          type: boolean
        year:
          type: string
          minLength: 1
      required:
        - asset_id
        - assigned_name
        - category
        - comment
        - manufacturer
        - status
        - vin
        - vin_validated
        - year
    organization:
      description: ''
      type: object
      x-examples:
        example-1:
          orgnisation_id: string
          orgnisation_name: string
          account_number: string
      properties:
        orgnisation_id:
          type: string
          minLength: 1
        orgnisation_name:
          type: string
          minLength: 1
        account_number:
          type: string
          minLength: 1
        type:
          type: string
      required:
        - orgnisation_id
        - orgnisation_name
        - account_number
    product:
      description: ''
      type: object
      x-examples:
        example-1:
          product_code: string
          product_name: string
          type: string
      properties:
        product_code:
          type: string
          minLength: 1
        product_name:
          type: string
          minLength: 1
        type:
          type: string
          minLength: 1
        manufacturer:
          $ref: '#/components/schemas/organization'
      required:
        - product_code
        - product_name
        - type
    campaign:
      description: ''
      type: object
      properties:
        campaign_id:
          type: string
          minLength: 1
        campaign_name:
          type: string
          minLength: 1
        description:
          type: string
          minLength: 1
        campaign_status:
          type: string
          minLength: 1
        last_command_days: {}
        created_by:
          type: string
          minLength: 1
        created_at:
          type: string
          minLength: 1
        customer_name: {}
        campaign_start_date: {}
      required:
        - campaign_id
        - campaign_name
        - description
        - campaign_status
        - created_by
        - created_at
      x-examples:
        example-1:
          campaign_id: 37baed2a-d082-4efa-acdc-b0ebe540570e
          campaign_name: 15 March test 02
          description: test 02 downgrade
          campaign_status: In progress
          last_command_days: null
          created_by: Brent Whitney
          created_at: '2021-03-15T05:23:53Z'
          customer_name: null
          campaign_start_date: null
    package:
      description: ''
      type: object
      x-examples:
        example-1:
          uuid: a8f4c211-3b3c-44b1-9f02-74a081fae092
          package_name: 09 April 01
          bin_version: 4.3.18_B0
          app_version: 2.8.0_B29
          mcu_version: 1.1.8_B16
          ble_version: ANY
          config1: EZTracPlus_CutL_12
          config2: Empty_01
          config3: Empty_01
          config4: Jersey_Telecom_msqa_02
          config1_crc: 14FF
          config2_crc: 66A9
          config3_crc: 66A9
          config4_crc: FFDD
          is_deleted: false
          created_by: Brent Whitney
          updated_by: Brent Whitney
          created_at: '2021-04-09T10:05:51Z'
      properties:
        package_is:
          type: string
          minLength: 1
        package_name:
          type: string
          minLength: 1
        bin_version:
          type: string
          minLength: 1
        app_version:
          type: string
          minLength: 1
        mcu_version:
          type: string
          minLength: 1
        ble_version:
          type: string
          minLength: 1
        config1:
          type: string
          minLength: 1
        config2:
          type: string
          minLength: 1
        config3:
          type: string
          minLength: 1
        config4:
          type: string
          minLength: 1
        config1_crc:
          type: string
          minLength: 1
        config2_crc:
          type: string
          minLength: 1
        config3_crc:
          type: string
          minLength: 1
        config4_crc:
          type: string
          minLength: 1
        is_deleted:
          type: boolean
        created_by:
          type: string
          minLength: 1
        updated_by:
          type: string
          minLength: 1
        created_at:
          type: string
          minLength: 1
      required:
        - package_is
        - package_name
        - bin_version
        - app_version
        - mcu_version
        - ble_version
        - config1
        - config2
        - config3
        - config4
        - config1_crc
        - config2_crc
        - config3_crc
        - config4_crc
        - is_deleted
        - created_by
        - updated_by
        - created_at
